# Generated by Django 4.2 on 2023-06-01 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mijoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('tel', models.CharField(max_length=20)),
                ('manzil', models.CharField(blank=True, max_length=100, null=True)),
                ('qarz', models.PositiveSmallIntegerField(default=0)),
                ('ombor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userapp.ombor')),
            ],
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('brend', models.CharField(blank=True, max_length=50)),
                ('o_narx', models.PositiveSmallIntegerField()),
                ('s_narx', models.PositiveSmallIntegerField()),
                ('miqdor', models.CharField(max_length=100)),
                ('olchov', models.CharField(max_length=30)),
                ('sana', models.DateField()),
                ('ombor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userapp.ombor')),
            ],
        ),
    ]
